# Prometheus configuration for Pharmacare Workspace Subscription monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Pharmacare API metrics
  - job_name: 'pharmacare-api'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:9216']
    scrape_interval: 30s

  # Node.js application metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # PM2 process metrics
  - job_name: 'pm2-metrics'
    static_configs:
      - targets: ['localhost:9209']
    scrape_interval: 15s

  # Redis metrics (if using Redis for caching)
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

  # Nginx metrics (if using Nginx as reverse proxy)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'pharmacare-custom-metrics'
    static_configs:
      - targets: ['localhost:5001']
    metrics_path: '/custom-metrics'
    scrape_interval: 30s
